<?php

namespace Gckabir\AwesomeCache;

class CacheTest extends TestCase
{
    public static function setUpBeforeClass()
    {
        echo "\n";
        echo "Setting Up\n";

        $config = array(
            'directory'    => __DIR__.'/../TestData/cache',
            );
        Cache::config($config);
    }

    public function testDirectoryPathAlwaysEndsWithATrailingSlash()
    {
        $directory = Cache::config('directory');

        $lastCharacter = substr($directory, -1, 1);
        $this->assertEquals($lastCharacter, '/');
    }

    public function testDirectoryIsAutoGeneratedWhenInstantiated()
    {
        $myCache = new Cache('testdata');

        $directory = Cache::config('directory');

        $directoryExists = is_dir($directory);

        $this->assertTrue($directoryExists);

    }

    public function testExceptionWhenBlankKeyIsPassedInTheConstructor()
    {
        $this->setExpectedException('Gckabir\AwesomeCache\CacheException');
        $myCache = new Cache('  ');
    }

    public function testStoringDataInTheCache()
    {
        $key = 'testdata1';
        $myCache = new Cache($key);

        if (file_exists($myCache->filePath())) {
            unlink($myCache->filePath());
        }

        $this->assertFileNotExists($myCache->filePath());

        $writtenSuccessfully =  $myCache->putInCache('this is just a test data');
        $this->assertTrue($writtenSuccessfully);

        $this->assertFileExists($myCache->filePath());

        return $key;
    }

    /**
     * @depends testStoringDataInTheCache
     */
    public function testIsCachedFunctionIsWorking($existingDataKey)
    {
        $myCache = new Cache($existingDataKey);
        $this->assertTrue($myCache->isCached());

        @unlink($myCache->filePath());
        // for an un existing file
        $anotherData = new Cache('some-unexisting-data');

        $this->assertFalse($anotherData->isCached());
    }

    public function testRetrievingDataFromCache()
    {
        $key = 'testdata2';

        //storing
        $myCache = new Cache($key);

        $dataToBeCached = array(
            'foo'    => 'Bar',
            'hello'    => 'World',
            );

        $writtenSuccessfully = $myCache->putInCache($dataToBeCached);
        $this->assertTrue($writtenSuccessfully);

        // retrieving
        $myCacheRetrival = new Cache($key);

        $retrievedData = $myCacheRetrival->cachedData();

        $this->assertNotEmpty($retrievedData);
        $this->assertEquals($dataToBeCached, $retrievedData);

        @unlink($myCacheRetrival->filePath());
    }

    public function testClearingSpecificCache()
    {
        $key = 'testdata3';

        $myCache = new Cache($key);

        $writtenSuccessfully = $myCache->putInCache('Foo Bar');
        $this->assertTrue($writtenSuccessfully);

        $this->assertFileExists($myCache->filePath());

        $myCache->purge();

        $this->assertFileNotExists($myCache->filePath());
    }

    public function testClearingAllCachedData() {

        $foo1 = new Cache('foo1');
        $writtenSuccessfully = $foo1->putInCache('Foo BAr 1');
        $this->assertTrue($writtenSuccessfully);

        $foo2 = new Cache('foo2');
        $writtenSuccessfully = $foo2->putInCache('Foo BAr 2');
        $this->assertTrue($writtenSuccessfully);

        $foo3 = new Cache('foo3');
        $writtenSuccessfully = $foo3->putInCache('Foo BAr 3');
        $this->assertTrue($writtenSuccessfully);

        Cache::clearAll();

        $this->assertFileNotExists($foo1->filePath());
        $this->assertFileNotExists($foo1->filePath());
        $this->assertFileNotExists($foo1->filePath());

    }

    public function testCountAllIsWorking() {

        Cache::clearAll();
        
        $this->assertEquals(0, Cache::countAll());

        $foo1 = new Cache('foo1');
        $writtenSuccessfully = $foo1->putInCache('Foo BAr 1');
        $this->assertTrue($writtenSuccessfully);

        $foo2 = new Cache('foo2');
        $writtenSuccessfully = $foo2->putInCache('Foo BAr 2');
        $this->assertTrue($writtenSuccessfully);

        $this->assertEquals(2, Cache::countAll());

        Cache::clearAll();

        $this->assertEquals(0, Cache::countAll());
    }

    public function testConfigurations() {

        $ourConfig  = array(
            'cacheExpiry'   => 44556,
            'serialize'     => true
            );

        // Setting configurations
        Cache::config($ourConfig);

        // retrieving all config
        $allConfigs = Cache::config();
        $this->assertTrue(is_array($allConfigs));

        $this->assertEquals($ourConfig['cacheExpiry'], $allConfigs['cacheExpiry']);
        $this->assertEquals($ourConfig['serialize'], $allConfigs['serialize']);

        // retrieving individual config items
        $this->assertEquals($ourConfig['cacheExpiry'], Cache::config('cacheExpiry'));
        $this->assertEquals($ourConfig['serialize'], Cache::config('serialize'));
    }

    public function testConfigThrowsExceptionForInvalidInput() {

        $this->setExpectedException('Gckabir\AwesomeCache\CacheException');
        Cache::config(56.2);
    }

    public function testKeyWorksProperly() {

        $myKey = 'hellodata';
        $myCache =  new Cache($myKey);

        $this->assertEquals($myKey, $myCache->key());
    }

    public function testIsUsableWorksCorrectly() {

        $myCache = new Cache('foodata123');
        $writtenSuccessfully = $myCache->putInCache('This is a test data');
        $this->assertTrue($writtenSuccessfully);

        $this->assertTrue( $myCache->isUsable() );

        Cache::clear($myCache->key()); // Same as doing $myCache->prune();

        $this->assertFalse($myCache->isCached());
    }

    public function testIsCachedAndUsable() {

        $myCache = new Cache('foodata124');

        $writtenSuccessfully = $myCache->putInCache('test data');
        $this->assertTrue($writtenSuccessfully);

        $this->assertTrue( $myCache->isCached() );
        $this->assertTrue( $myCache->isUsable() );
        $this->assertTrue( $myCache->isCachedAndUsable() );

        Cache::clear($myCache->key()); // Same as doing $myCache->prune();

        $this->assertFalse($myCache->isCached());
    }

    public function testPuttingNonScalarDataWhenSerializationIsDisabled() {
        Cache::config(array(
            'serialize' => false
            ));

        $myCache = new Cache('foodata1245');

        // scalar data
        $scalarData = 'Hello World';
        $writtenSuccessfully = $myCache->putInCache($scalarData);
        
        $this->assertEquals($scalarData, $myCache->cachedData());
        $this->assertTrue($writtenSuccessfully);
        $myCache->purge();
        $this->assertFileNotExists($myCache->filePath());

        // non-scalar data
        $nonScalarData = array('foo'    => 'bar');

        $this->setExpectedException('Gckabir\AwesomeCache\CacheException');

        $writtenSuccessfully = $myCache->putInCache($nonScalarData);

        $this->assertFalse($writtenSuccessfully);

    }

    public function testDurationWorksCorrectly() {

        $myCache = new Cache('foodata123456');
        $writtenSuccessfully = $myCache->putInCache('test data');
        $this->assertTrue($writtenSuccessfully);

        sleep(1);

        $this->assertTrue( $myCache->duration() > 0 );

        $myCache->purge();
    }

    public static function tearDownAfterClass()
    {
        echo "\n";
        echo "Tearing Down\n";
        Cache::clearAll();
        rmdir(Cache::config('directory'));
    }

}
