# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*

build:
    environment:
        php:
            version: "5.6.0", "5.5.14", "5.4.30", "hhvm"        # Common versions: 5.4.28, 5.5.12, or hhvm